#!/bin/bash
set -e

branches=()

IFS=$'\n' read -r -d '' -a branches < <( git branch | cut -c 3- && printf '\0' )

if [[ " ${branches[*]} " =~ " main " ]]; then
    main="main"
elif [[ " ${branches[*]} " =~ " master " ]]; then
    main="master"
elif [[ " ${branches[*]} " =~ " dev " ]]; then
    main="dev"
fi

if [ -z $main ]; then
  echo "Could not determine main branch"
  exit 1
fi

echo $main